title: Muhammad Zaki Fahrezi
description: Portofolio Web Personal Zaki
baseurl: "" # jika diakses lewat m-zakifahrezi.github.io (tanpa repo name), biarkan kosong
url: "https://m-zakifahrezi.github.io/" # ganti sesuai URL GitHub Pages kamu

# Konfigurasi untuk SCSS
sass:
  sass_dir: _sass

# Informasi pemilik
author:
  name: Muhammad Zaki Fahrezi
  email: zakyfahrezi53@email.com

# Pilihan untuk GitHub Pages
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
