title: Home
baseurl: ""
url: "https://m-zakifahrezi.github.io/"

sass:
  sass_dir: _sass
  style: compressed

theme: null

collections:
  id:
    output: true
    permalink: /id/:title/
  en:
    output: true
    permalink: /en/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
